name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      working-directory: ./js
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      working-directory: ./js
      run: pnpm install
    - name: Install Playwright Browsers
      working-directory: ./js
      run: pnpm exec playwright install --with-deps
    - name: Run tests
      run: make build && make test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./js/playwright-report/
        retention-days: 30
